appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: uDYyViBV95My74dWDK16C9s5+OcP64gEh739cJscZdM7/muvyrVa3XZBgPg9g6dHK3ApLOgtGH9JOorzim/tZCXW/7AWUBmeyeWqLmKwD28qmv+mM9IDF1TLp9RhM/lms8W4tNhwQGbs8qeg9aKRJrmf8EphRXwYGJf/oeh1XyU9uDwZqK9Bb8tjQAWGktt2v1gaVFU+T96LEytfb5Mk2Bj5d7pM782djWED9kez/w5SXFYit2H6gGrDclrvz0VEj0SM7ry/sfIgWrpFGtdPhxFLWdeWTSW1lYj+NBfHt8qlvOl3b8u0Wfs0XFx3DXjyjm+lwykwJjc/0IHc8+9tZCE7hhwjLtTvnkn6+Cuj7mEmXin9yeWOtSzlIGrQ0jSFqdfq+Wg+vyEfZ6QwXNwf57s53jHN9/lSyKXXMl4aqLon9dv9+P8DLxtr3s1Kr0USm9+6fv8FubEaTnnjyAxQG3dXS82hmpBNIcF/oUoU99YMERxnd/FLKdLVzk3//Vxc8z3QgFDBcRqNAAxa0GNhtMr2Ho0NxlCRIGsxWvNi6ORQC6A+BRyJhIBBfBAlDmeTFWCFLwWY5My9NXAqzHxJdAzp+J6VZU2tT260ADxgFjBkhRxgPjBnJYecA/BTIt3r8rjeY6wJt2cT0HQXulgclkSEGDQW58tVMHyeVlRBSyE=}
bot:
  automerge: true
