travis:
  secure:
    BINSTAR_TOKEN: p9JmcIJ/FphBekhKqkqtth0QdjMpVJfHZfGSSx5IGlNpMOAp8tHgNw2uQk6YS84wVqImcw4Nz6eSbY0l4kWLFVE9irWzMRypDoYqUXn2K+HgTQ7JLjeEa2W6GhZfZCJ8TvZNLl5DrZDm26I5sNf4Uv4jE5zEGMqgzi0airEa9oKwuW0j+MdkChmoXen06/2/wEC74VZHXfMhRU26NMFEqk4r/oCXfN+sJsjDRDUqwaoTF23YJM9HxYRsTwUGVKQixf24lbtRkmuk9svKRSHl6LDDFaOdKT1C2jYr1rWeHueiltwxhoW4pAoXOanpWfxEixsePNa6976nwntDsOVz4ItdqCgbOhidmplFQvKv4dnhisg5XI6K8PRjtXitJON/eJB6lABbb95Li2p5wpBGytpZvJrakMuMy8xYb22D1hsQoSMgTk7kTeUkjSd0txUqW3kjExD9Z5nSl+EPqxbtMVY/Skh81lhmQcHtZJHpkVTVhUgqSNyZ0bA9i3MSze7JApalyZHCPaLtLqghb298lh6rEC4PjxNORG71IuHATCYu66UnrR3GeXgBqZgB3BroG+r7j1EjW2t4gD7tPd5TioxxUZWLwGmyf1aWCAQ9NinCLcQM7y9xc2/Z5TCMLmY5mCpUEdX7tan+34PoCVSOv1fRoiH/0iF1wt3vxlFKRNs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
